language: perl

sudo: false

perl:
- '5.8'
- '5.10'
- '5.12'
- '5.14'
- '5.16'
- '5.18'
- '5.20'
- '5.22'
- '5.24'
- '5.26'
- '5.28'
- '5.30'

before_install:
  - 'cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)'
  - 'cpanm Module::Build::Tiny'

notifications:
  email: false
  slack:
    secure: Rpw5hABv8AMCzoHMXaZasSpB5WPqAIz0iOy0gUGiPr/WwmotO0Uo76xxNIsG1BvREF01hUJUq/I7SRKs75XcHMN8cWGd6nFYPZhE7uDf6330go/lu3PX+g24+t6z+MFy1D4s1HjTxzDqXDcGAwLYRoPbO/1og+WfEsDCCg0HfdsjwEPJjar8giClkcBNot5LsLP5JkKzBaTksqU6uzt0MwJOqkHVLgP6upC7HbAamSjmdlEemSCJOfNXxubVm0f1gYyAc70xEZ6Y1LbKFxHjsPE6MGLbPPhpAkl1zfKbExszDu9+imvJYizgxe+LzkCEVoMkxM3arJtuigPSQgOWPUtRGIl6Frmk3q/0VNk6PXcgAW05tfn8RQErQLyhZar5z5Iy+cSMVZ+PyjCPwp9C9grQHNogLgY2yc85bm762Fae9SQCZbNvIb6cUE9KOUF0ak37K7YOw1jH6iF4qyoif+XYnzQYvW1NQqH8KzkxiJU9U6gKz/rhfJluXSJs2Tg9vc0QsXXYM8gkP56Fryt2SbfccHEsVfeED6pe/FXToVS/2dnkDf2Wap3yoWyAoE+zAV0mh98vilyy/ZHpprJPguMKcBe3qydBKuhev3tTuSm7Bs/q73X6rsKNcGarP6OHRnlgeCfUsXtMNORY88e//m318eGf8LW8Lde++Nmx0Qs=
